[programs.localnet]
propertymanager = "9GMk42U1C3tZCUFNLQbEEPfqUgpnrYFDLfLiL8pzu4DT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
