[programs.devnet]
propertymanager = "H1wEdLaMbs2UYu6dWwRP1zmhJCh1JuBLEc9QA69h9Wup"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

